name: Autobump Formulas and Casks

on:
#   schedule:
#     - cron: '0 */12 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-14
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@df6d545fcfd1ceb62b7e122933a8a4a0cf7eaba1
        with:
          # Required, custom personal GitHub access token with only the 'public_repo' scope enabled
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} # ${{ secrets.CUSTOM_PERSONAL_ACCESS_TOKEN }}
          # Optional, will commit with this user name
          user_name: risc
          # Optional, will commit with this user email
          user_email: risc@fastmail.com
          # Optional, use the origin repository instead of forking
          no_fork: true
          # Bump all outdated formulae in this tap
          tap: 0risc/homebrew-tap-test
          # Optional, if don't want to check for already open PRs
          force: false
          # Need to set this input if want to use `brew livecheck`
          livecheck: true
