name: Autobump Formulas and Casks

on:
#   schedule:
#     - cron: '0 */12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-latest
    env:
      HOMEBREW_TEST_BOT_AUTOBUMP: 1
    steps:
      - name: Update Homebrew formula
        uses: 0risc/action-homebrew-bump-formula@fix-force
        with:
          # Required, custom personal GitHub access token with only the 'public_repo' scope enabled
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} # ${{ secrets.CUSTOM_PERSONAL_ACCESS_TOKEN }}
          # Optional, will commit with this user name
          user_name: risc
          # Optional, will commit with this user email
          user_email: risc@fastmail.com
          # Optional, use the origin repository instead of forking
          no_fork: true
          # Bump all outdated formulae in this tap
          tap: 0risc/homebrew-tap-test
          # Optional, if don't want to check for already open PRs
          force: true
          # Need to set this input if want to use `brew livecheck`
          livecheck: true
          message: Created with `brew bump-formula-pr` and `action-homebrew-bump-formula`.

      - name: Update Homebrew cask
        uses: eugenesvk/action-homebrew-bump-cask@cc260684c6e41de1af9522a0f4dcb4f321a17f33
        with:
          # Required, custom GitHub access token with only the 'public_repo' scope enabled
          token    	: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          # Bump all outdated casks in this tap
          tap      	: 0risc/homebrew-tap-test
          # Need to set this input if want to use `brew livecheck`
          livecheck	: true
