name: Add pr-pull label to merge

on:
  pull_request:
    paths:
    - 'Formula/**'
  pull_request_target:
    types:
      - labeled

jobs:
  check-for-label:
    runs-on: ubuntu-latest
    steps:
      # unclear why `github.event_name == 'pull_request' &&` is required but it is
      - run: exit 0
        if: github.event_name == 'pull_request' && contains( github.event.pull_request.labels.*.name, 'pr-pull' )

      - run: exit 1
        if: github.event_name == 'pull_request' && !contains( github.event.pull_request.labels.*.name, 'pr-pull' )
