name: Add pr-pull label to merge

on:
  pull_request:
    paths:
    - 'Formula/**'

jobs:
  test-for-label:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
        if: contains( github.event.pull_request.labels.*.name, 'pr-pull' )

      - run: exit 1
        if: !contains( github.event.pull_request.labels.*.name, 'pr-pull' )

  check-for-label:
    if: always()
    needs:
      - test-for-label
    runs-on: ubuntu-latest
    steps:
        - name: Determine whether the needed jobs succeeded or failed
          uses: re-actors/alls-green@release/v1
          with:
            jobs: ${{ toJSON(needs) }}
